import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from '@/components/allPageComponent/navbar'
import {AiOutlineCaretDown} from '@react-icons/all-files/ai/AiOutlineCaretDown'

const inter = Inter({ subsets: ['latin'] })

function Flow()
{
  function WhyIUse(){
    return(
      <div id="usage" className='w-full h-screen flex flex-row flex-wrap bg-red-500'>
      </div>
    );
  }
  return(
    <div className='w-full h-screen overflow-scroll bg-black'>
      <div className='w-full h-screen bg-pattern flex flex-col gap-y-2 justify-center items-center'>
        <span className='text-9xl'>Alha UI</span>
        <span>Tailwind Based UI Library</span>
        <span className='flex flex-row justify-center items-center'>Learn More &nbsp; <a href="#usage"><AiOutlineCaretDown className='text-2xl hover:cursor-pointer'/></a> </span>
      </div>
      <WhyIUse></WhyIUse>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full min-h-screen bg-slate-200 flex'>
        <Navbar></Navbar>
        <Flow></Flow>
      </main>
    </>
  )
}
